import { afterEach, describe, expect, it, vi } from 'vitest';
import { createPlanningScenario, generateHistoricalYieldForecast, generateReport, getTenorYieldCurve, transitionPlanningScenario, validCustomerToken, validForecastPoolId, validGeneration, validPlanningScenario, validPublication } from './reporting-api';
afterEach(() => vi.restoreAllMocks());
describe('regulatory reporting', () => {
  it('validates generation and publication evidence', () => { expect(validGeneration({ reportType: 'REGULATORY_MONTHLY', period: '2026-09' })).toBe(true); expect(validPublication({ evidenceDocumentId: '8c86d06e-2c2e-4aac-93d7-465c338232d9', justification: 'Contrôle réglementaire conforme' })).toBe(true); expect(validPublication({ evidenceDocumentId: '------------------------------------', justification: 'Justification suffisante' })).toBe(false); expect(validPublication({ evidenceDocumentId: 'invalid', justification: 'court' })).toBe(false); });
  it('sends an idempotent generation command', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ regulatoryReportId: 'report-1', state: 'GENERATED' }))); await generateReport({ reportType: 'REGULATORY_MONTHLY', period: '2026-09' }); const [, init] = fetchMock.mock.calls[0]!; expect(new Headers(init?.headers).get('idempotency-key')).toMatch(/^[0-9a-f-]{36}$/); });
  it('validates and creates a twelve-month planning scenario', async () => { const command = { poolId: 'POOL-1', kind: 'CENTRAL' as const, version: 1, startMonth: '2026-10', assumptions: { monthlyResourceGrowthPercent: '1', annualYieldPercent: '6', monthlyPlacementGrowthPercent: '2' } }; expect(validPlanningScenario(command)).toBe(true); expect(validPlanningScenario({ ...command, poolId: 'x' })).toBe(false); const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ scenarioId: 'scenario-1', status: 'DRAFT' }))); await createPlanningScenario(command); expect(fetchMock.mock.calls[0]?.[0]).toBe('/api/core/reporting/planning-scenarios'); });
  it('transitions a scenario idempotently to an explicit target state', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ status: 'SUBMITTED' }))); await transitionPlanningScenario('scenario-1', { targetStatus: 'SUBMITTED' }); const [, init] = fetchMock.mock.calls[0]!; expect(fetchMock.mock.calls[0]?.[0]).toContain('/scenario-1/transitions'); expect(new Headers(init?.headers).get('idempotency-key')).toMatch(/^[0-9a-f-]{36}$/); expect(init?.body).toBe(JSON.stringify({ targetStatus: 'SUBMITTED' })); });
  it('generates a pool-only historical forecast', async () => { expect(validForecastPoolId('POOL:001')).toBe(true); expect(validForecastPoolId('x')).toBe(false); const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ forecastId: 'forecast-1', points: [] }))); await generateHistoricalYieldForecast('POOL:001'); expect(fetchMock.mock.calls[0]?.[0]).toBe('/api/core/reporting/historical-yield-forecasts/POOL%3A001'); });
  it('loads a customer-scoped tenor curve only with a tokenized identifier', async () => { expect(validCustomerToken('tok_1234567890abcdef')).toBe(true); expect(validCustomerToken('customer-raw-id')).toBe(false); const controller = new AbortController(); const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ scope: 'CUSTOMER', points: [] }))); await getTenorYieldCurve('POOL:001', 'tok_1234567890abcdef', controller.signal); expect(fetchMock.mock.calls[0]?.[0]).toContain('customerToken=tok_1234567890abcdef'); expect(fetchMock.mock.calls[0]?.[1]).toEqual(expect.objectContaining({ signal: controller.signal })); });
  it('surfaces a correlation reference from API errors', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ detail: 'Publication refusée', correlationId: 'corr-42' }), { status: 409 })); await expect(generateReport({ reportType: 'REGULATORY_MONTHLY', period: '2026-09' })).rejects.toThrow('Publication refusée (référence : corr-42)'); });
});
