'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { validReconciliation, type ReconciliationCommand, type ReconciliationResult } from './reconciliation-api';
import { ReconciliationError, ReconciliationStatus } from './reconciliation-feedback';
import styles from '../products/products.module.css';
const initial: ReconciliationCommand = { businessDate: new Date().toISOString().slice(0, 10), currency: 'DZD', generalLedgerAmount: '', sourceReference: '', sourceChecksumSha256: '' };
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function validResult(value: unknown): value is ReconciliationResult { return isRecord(value) && typeof value.reconciliationId === 'string' && value.reconciliationId.trim().length > 0 && typeof value.state === 'string' && value.state.trim().length > 0 && typeof value.difference === 'string'; }
export async function reconcileForConsole(command: ReconciliationCommand, signal: AbortSignal): Promise<ReconciliationResult> { const correlationId = crypto.randomUUID(); const response = await fetch('/api/core/accounting/reconciliations', { method: 'POST', signal, headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID(), 'x-correlation-id': correlationId }, body: JSON.stringify(command) }); const payload: unknown = await response.json().catch(() => undefined); const problem = isRecord(payload) ? payload : {}; const detail = typeof problem.detail === 'string' && problem.detail.trim() ? problem.detail : typeof problem.title === 'string' && problem.title.trim() ? problem.title : `Erreur HTTP ${response.status}`; const reference = typeof problem.correlationId === 'string' && problem.correlationId.trim() ? problem.correlationId : response.headers.get('x-correlation-id') ?? correlationId; if (!response.ok) throw new Error(`${detail} (référence : ${reference})`); if (!validResult(payload)) throw new Error(`Réponse de rapprochement invalide. (référence : ${reference})`); return payload; }
type ReconciliationCallbacks = { loading: () => void; success: (result: ReconciliationResult) => void; failure: (message: string) => void; settled: () => void };
export class ReconciliationConsoleOperation { private active?: { readonly token: symbol; readonly controller: AbortController }; async run(operation: (signal: AbortSignal) => Promise<ReconciliationResult>, callbacks: ReconciliationCallbacks): Promise<boolean> { if (this.active) return false; const current = { token: Symbol('reconciliation-command'), controller: new AbortController() }; this.active = current; callbacks.loading(); try { const result = await operation(current.controller.signal); if (this.active === current && !current.controller.signal.aborted) callbacks.success(result); } catch (cause) { if (this.active === current && !current.controller.signal.aborted) callbacks.failure(cause instanceof Error ? cause.message : 'Erreur inattendue.'); } finally { if (this.active === current) { this.active = undefined; if (!current.controller.signal.aborted) callbacks.settled(); } } return true; } cancel(): void { this.active?.controller.abort(); this.active = undefined; } }
export function ReconciliationConsole() {
  const [command, setCommand] = useState(initial), [submitted, setSubmitted] = useState<ReconciliationCommand>(), [result, setResult] = useState<ReconciliationResult>(), [busy, setBusy] = useState(false), [attempted, setAttempted] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  const operations = useRef<ReconciliationConsoleOperation>(null);
  if (!operations.current) operations.current = new ReconciliationConsoleOperation();
  useEffect(() => () => operations.current?.cancel(), []);
  const change = (key: keyof ReconciliationCommand, value: string) => setCommand({ ...command, [key]: value });
  async function submit(event: FormEvent) {
    event.preventDefault(); setAttempted(true);
    if (!validReconciliation(command)) return setError('Vérifiez la date, la devise, le montant, la référence et le checksum SHA-256.');
    const snapshot = { ...command };
    await operations.current!.run((signal) => reconcileForConsole(snapshot, signal), {
      loading: () => { setBusy(true); setError(''); setMessage(''); setResult(undefined); setSubmitted(undefined); },
      success: (reconciled) => { setResult(reconciled); setSubmitted(snapshot); setMessage(`Rapprochement ${reconciled.state}.`); },
      failure: setError,
      settled: () => setBusy(false),
    });
  }
  return <div className={styles.grid} aria-busy={busy}><section className={styles.card}><h2>Lancer un rapprochement</h2><form className={styles.form} onSubmit={submit}><div className={styles.row}><label className={styles.field}>Date métier<input type="date" value={command.businessDate} onChange={(e) => change('businessDate', e.target.value)} /></label><label className={styles.field}>Devise<input maxLength={3} value={command.currency} onChange={(e) => change('currency', e.target.value.toUpperCase())} /></label></div><label className={styles.field}>Montant du grand livre<input inputMode="decimal" value={command.generalLedgerAmount} onChange={(e) => change('generalLedgerAmount', e.target.value)} /></label><label className={styles.field}>Référence de la source<input value={command.sourceReference} onChange={(e) => change('sourceReference', e.target.value)} /></label><label className={styles.field}>Checksum SHA-256 de la source<input className={styles.checksum} value={command.sourceChecksumSha256} onChange={(e) => change('sourceChecksumSha256', e.target.value.toLowerCase())} /></label><button className={styles.button} disabled={busy}>{busy ? 'Rapprochement…' : 'Rapprocher les écritures'}</button></form><ReconciliationError message={error} /><ReconciliationStatus message={message} /></section><section className={styles.card}><h2>Écart comptable</h2>{result && submitted ? <div className={styles.product}><span className={styles.badge}>{result.state}</span><dl><dt>Écart</dt><dd>{result.difference} {submitted.currency}</dd><dt>Rapprochement</dt><dd>{result.reconciliationId}</dd><dt>Source</dt><dd>{submitted.sourceReference}</dd></dl></div> : <p className={styles.hint}>Le backend comparera la source certifiée au grand livre et conservera la preuve du rapprochement.</p>}</section></div>;
}
