import { afterEach, describe, expect, it, vi } from 'vitest';
import { acknowledgeAccountingEvent, emitAccountingEvent, reconcile, validAccountingEvent, validAcknowledgement, validReconciliation, type AccountingEventCommand, type ReconciliationCommand } from './reconciliation-api';
const valid: ReconciliationCommand = { businessDate: '2026-09-08', currency: 'DZD', generalLedgerAmount: '1250000.25', sourceReference: 'CBS-20260908', sourceChecksumSha256: 'b'.repeat(64) };
afterEach(() => vi.restoreAllMocks());
describe('accounting reconciliation', () => {
  it('requires a verifiable source and an exact business date', () => { expect(validReconciliation(valid)).toBe(true); expect(validReconciliation({ ...valid, sourceChecksumSha256: 'invalid' })).toBe(false); expect(validReconciliation({ ...valid, businessDate: '2026-02-30' })).toBe(false); });
  it('sends an idempotent reconciliation', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ reconciliationId: 'rec-1', state: 'MATCHED', difference: '0' }))); await reconcile(valid); const [, init] = fetchMock.mock.calls[0]!; expect(new Headers(init?.headers).get('idempotency-key')).toMatch(/^[0-9a-f-]{36}$/); });
});
describe('accounting event lifecycle', () => {
  const event: AccountingEventCommand = { runId: 'run-1', poolId: 'pool-1', productId: 'product-1', eventType: 'REVENUE', eventId: 'event-1', entityId: 'entity-1', businessDate: '2026-09-08', currencyScale: 2, lines: [{ accountCode: 'POOL:REVENUE', currency: 'DZD', debit: '100', credit: '0' }, { accountCode: 'GL:REVENUE', currency: 'DZD', debit: '0', credit: '100' }] };
  it('validates exact journal balance, scale and rejection evidence', () => { expect(validAccountingEvent(event)).toBe(true); expect(validAccountingEvent({ ...event, lines: [{ ...event.lines[0], debit: '99' }, event.lines[1]] })).toBe(false); expect(validAccountingEvent({ ...event, currencyScale: 2, lines: [{ ...event.lines[0], debit: '100.001' }, event.lines[1]] })).toBe(false); expect(validAcknowledgement({ action: 'REJECTED', externalReference: 'GL-1', reason: 'Motif documenté' })).toBe(true); expect(validAcknowledgement({ action: 'REJECTED', externalReference: 'GL-1' })).toBe(false); });
  it('emits then acknowledges through scoped BFF routes', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(new Response(JSON.stringify({ journalEntryId: '00000000-0000-4000-8000-000000000001', acknowledgementState: 'PENDING' }))).mockResolvedValueOnce(new Response(JSON.stringify({ acknowledgementState: 'ACKNOWLEDGED' }))); await emitAccountingEvent(event); await acknowledgeAccountingEvent('00000000-0000-4000-8000-000000000001', { action: 'ACKNOWLEDGED', externalReference: 'GL-1' }); expect(fetchMock.mock.calls[0]?.[0]).toBe('/api/core/accounting/events'); expect(fetchMock.mock.calls[1]?.[0]).toContain('/acknowledgements'); });
  it('surfaces correlated lifecycle errors', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValue(new Response(JSON.stringify({ detail: 'Transition interdite', correlationId: 'corr-7' }), { status: 409 })); await expect(acknowledgeAccountingEvent('journal-1', { action: 'ACKNOWLEDGED', externalReference: 'GL-1' })).rejects.toThrow('Transition interdite (référence : corr-7)'); });
});
