import type {Locale} from './config';

const fr = {
  localeName: 'Français', language: 'Langue', skip: 'Aller au contenu principal', navigation: 'Navigation principale', closeNav: 'Fermer la navigation', openNav: 'Ouvrir la navigation',
  productName: 'Gestion du partage des profits', userFallback: 'Utilisateur', userRole: 'Utilisateur PMS', pilotage: 'Pilotage', management: 'Gestion', control: 'Contrôle', restitution: 'Restitution',
  dashboard: 'Tableau de bord', closings: 'Arrêtés', products: 'Produits', allocations: 'Allocations', calculations: 'Calcul et partage', risk: 'Risque et ALM', sharia: 'Conformité Charia', reconciliation: 'Rapprochements', reporting: 'Reporting', audit: 'Piste d’audit',
  period: 'Période', month: 'Août 2026', operational: 'Services opérationnels', overview: 'Vue consolidée', hello: 'Bonjour', hero: 'Supervisez la distribution des profits, les contrôles de conformité et l’avancement de l’arrêté depuis un point d’entrée unique.',
  cycle: 'Cycle de traitement', ingestion: 'Ingestion', allocation: 'Allocation', calculation: 'Calcul', validation: 'Validation', publication: 'Publication', keyIndicators: 'Indicateurs clés', consolidatedAt: 'Situation consolidée au 29 août 2026',
  outstanding: 'Encours participatifs', outstandingDetail: '+4,8 % sur la période', distributable: 'Revenus distribuables', revenuePeriod: 'Période août 2026', portfolioDcr: 'DCR portefeuille', threshold: 'Seuil interne : 1,10×', actions: 'Actions à traiter', controls: '2 contrôles prioritaires',
  operationalTracking: 'Suivi opérationnel', trackingDetail: 'Revenus et tâches de contrôle de la période', revenueEvolution: 'Évolution des revenus distribuables', upToDate: 'À jour', chartLabel: 'Les revenus et distributions progressent globalement de mars à août', revenues: 'Revenus', distributed: 'Distribués', workQueue: 'File de travail', sevenActions: '7 actions',
  task1: 'Valider la simulation Mudaraba', task1Detail: 'Contrôle financier · prioritaire', task2: 'Revoir l’écart de rapprochement', task2Detail: 'Compte 472100 · 1,2 M DZD', task3: 'Approuver le rapport réglementaire', task3Detail: 'Workflow Maker/Checker'
} as const;

const en: Record<keyof typeof fr, string> = {
  localeName: 'English', language: 'Language', skip: 'Skip to main content', navigation: 'Primary navigation', closeNav: 'Close navigation', openNav: 'Open navigation', productName: 'Profit Sharing Management', userFallback: 'User', userRole: 'PMS user', pilotage: 'Steering', management: 'Management', control: 'Control', restitution: 'Reporting', dashboard: 'Dashboard', closings: 'Closings', products: 'Products', allocations: 'Allocations', calculations: 'Calculation and sharing', risk: 'Risk and ALM', sharia: 'Sharia compliance', reconciliation: 'Reconciliations', reporting: 'Reporting', audit: 'Audit trail', period: 'Period', month: 'August 2026', operational: 'Services operational', overview: 'Consolidated view', hello: 'Hello', hero: 'Monitor profit distribution, compliance controls and closing progress from a single entry point.', cycle: 'Processing cycle', ingestion: 'Ingestion', allocation: 'Allocation', calculation: 'Calculation', validation: 'Validation', publication: 'Publication', keyIndicators: 'Key indicators', consolidatedAt: 'Consolidated position at 29 August 2026', outstanding: 'Participating assets', outstandingDetail: '+4.8% over the period', distributable: 'Distributable income', revenuePeriod: 'August 2026 period', portfolioDcr: 'Portfolio DCR', threshold: 'Internal threshold: 1.10×', actions: 'Actions required', controls: '2 priority controls', operationalTracking: 'Operational tracking', trackingDetail: 'Income and control tasks for the period', revenueEvolution: 'Distributable income trend', upToDate: 'Up to date', chartLabel: 'Income and distributions generally increase from March to August', revenues: 'Income', distributed: 'Distributed', workQueue: 'Work queue', sevenActions: '7 actions', task1: 'Validate the Mudaraba simulation', task1Detail: 'Financial control · priority', task2: 'Review reconciliation discrepancy', task2Detail: 'Account 472100 · DZD 1.2m', task3: 'Approve the regulatory report', task3Detail: 'Maker/Checker workflow'
};

const ar: Record<keyof typeof fr, string> = {
  localeName: 'العربية', language: 'اللغة', skip: 'الانتقال إلى المحتوى الرئيسي', navigation: 'التنقل الرئيسي', closeNav: 'إغلاق قائمة التنقل', openNav: 'فتح قائمة التنقل', productName: 'إدارة تقاسم الأرباح', userFallback: 'مستخدم', userRole: 'مستخدم المنصة', pilotage: 'القيادة', management: 'الإدارة', control: 'الرقابة', restitution: 'التقارير', dashboard: 'لوحة القيادة', closings: 'الإقفالات', products: 'المنتجات', allocations: 'التخصيصات', calculations: 'الحساب والتقاسم', risk: 'المخاطر وإدارة الأصول والخصوم', sharia: 'الامتثال الشرعي', reconciliation: 'المطابقات', reporting: 'التقارير', audit: 'مسار التدقيق', period: 'الفترة', month: 'أغسطس 2026', operational: 'الخدمات تعمل', overview: 'نظرة موحدة', hello: 'مرحباً', hero: 'راقب توزيع الأرباح وضوابط الامتثال وتقدم الإقفال من نقطة دخول واحدة.', cycle: 'دورة المعالجة', ingestion: 'الاستيراد', allocation: 'التخصيص', calculation: 'الحساب', validation: 'التحقق', publication: 'النشر', keyIndicators: 'المؤشرات الرئيسية', consolidatedAt: 'الوضعية الموحدة في 29 أغسطس 2026', outstanding: 'الأصول التشاركية', outstandingDetail: '+4.8٪ خلال الفترة', distributable: 'الإيرادات القابلة للتوزيع', revenuePeriod: 'فترة أغسطس 2026', portfolioDcr: 'نسبة تغطية التوزيع', threshold: 'الحد الداخلي: 1.10×', actions: 'الإجراءات المطلوبة', controls: 'عمليتا رقابة ذات أولوية', operationalTracking: 'المتابعة التشغيلية', trackingDetail: 'إيرادات ومهام الرقابة للفترة', revenueEvolution: 'تطور الإيرادات القابلة للتوزيع', upToDate: 'محدّث', chartLabel: 'ترتفع الإيرادات والتوزيعات إجمالاً من مارس إلى أغسطس', revenues: 'الإيرادات', distributed: 'الموزع', workQueue: 'قائمة العمل', sevenActions: '7 إجراءات', task1: 'التحقق من محاكاة المضاربة', task1Detail: 'رقابة مالية · أولوية', task2: 'مراجعة فرق المطابقة', task2Detail: 'الحساب 472100 · 1.2 مليون دج', task3: 'اعتماد التقرير التنظيمي', task3Detail: 'مسار المُعِد/المراجع'
};

export type Messages = Record<keyof typeof fr, string>;
export const messages: Record<Locale, Messages> = {fr, ar, en};
export function getMessages(locale: Locale): Messages { return messages[locale]; }
