'use client';
import { useState } from 'react';
import { approveExport, createExport, generateExport, type SecureExportTransition, type GeneratedSecureExport } from './audit-api';
import styles from '../products/products.module.css';
export function AuditConsole() {
  const [reportType, setReportType] = useState('AUDIT_TRAIL'), [format, setFormat] = useState<'PDF'|'XLSX'|'CSV'|'API'>('CSV'), [scope, setScope] = useState<'SINGLE'|'BULK'>('SINGLE'), [request, setRequest] = useState<SecureExportTransition>(), [generated, setGenerated] = useState<GeneratedSecureExport>(), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function run(work: () => Promise<void>) { setBusy(true); setError(''); try { await work(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erreur inattendue.'); } finally { setBusy(false); } }
  return <div className={styles.grid}><section className={styles.card}><h2>Demander un export sécurisé</h2><div className={styles.form}><label className={styles.field}>Type de rapport<input value={reportType} onChange={(e) => setReportType(e.target.value.toUpperCase())} /></label><div className={styles.row}><label className={styles.field}>Format<select value={format} onChange={(e) => setFormat(e.target.value as typeof format)}>{['PDF','XLSX','CSV','API'].map(v => <option key={v}>{v}</option>)}</select></label><label className={styles.field}>Portée<select value={scope} onChange={(e) => setScope(e.target.value as typeof scope)}><option>SINGLE</option><option>BULK</option></select></label></div><button className={styles.button} disabled={busy} onClick={() => void run(async () => setRequest(await createExport({ reportType, format, scope })))}>Créer la demande</button></div>{error && <p className={`${styles.notice} ${styles.error}`} role="alert">{error}</p>}{request && <div className={styles.product}><span className={styles.badge}>{request.status}</span><dl><dt>Export</dt><dd>{request.exportId}</dd></dl></div>}</section><section className={styles.card}><h2>Contrôle et génération</h2><p className={styles.hint}>Les exports massifs exigent l’approbation renforcée d’un Checker distinct.</p><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy || !request || scope !== 'BULK'} onClick={() => void run(async () => { await approveExport(request!.exportId); setRequest({ ...request!, status: 'APPROVED' }); })}>Approuver l’export massif</button><button className={styles.button} disabled={busy || !request || request.status !== 'APPROVED'} onClick={() => void run(async () => setGenerated(await generateExport(request!.exportId, { dataset: { columns: [{ key: 'reference', label: 'Référence' }], rows: [{ reference: request!.exportId }] } })))}>Générer la preuve</button></div>{generated && <div className={styles.product}><span className={styles.badge}>{generated.status}</span><p className={styles.checksum}>{generated.checksumSha256}</p></div>}</section></div>;
}
