'use client';
import { FormEvent, useState } from 'react';
import { shariaRequest, shariaValidationMessage, type ShariaAction, type ShariaReviewTransition } from './sharia-api';
import styles from '../products/products.module.css';
type Mode = ShariaAction['kind'];
export function ShariaConsole() {
  const [mode, setMode] = useState<Mode>('submit'), [reviewId, setReviewId] = useState(''), [resourceType, setResourceType] = useState('INVESTMENT_PRODUCT'), [resourceId, setResourceId] = useState(''), [opinion, setOpinion] = useState(''), [decision, setDecision] = useState('APPROVED'), [justification, setJustification] = useState(''), [evidenceDocumentId, setEvidenceDocumentId] = useState(''), [result, setResult] = useState<ShariaReviewTransition>(), [busy, setBusy] = useState(false), [error, setError] = useState('');
  function action(): ShariaAction { if (mode === 'submit') return { kind: mode, command: { resourceType, resourceId } }; if (mode === 'review') return { kind: mode, reviewId, command: { opinion } }; return { kind: mode, reviewId, command: { decision, justification, evidenceDocumentId } }; }
  async function submit(event: FormEvent) { event.preventDefault(); const request = action(), validation = shariaValidationMessage(request); setError(''); setResult(undefined); if (validation) return setError(validation); setBusy(true); try { const transition = await shariaRequest(request); setResult(transition); if (mode === 'submit') setReviewId(transition.reviewId); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erreur inattendue.'); } finally { setBusy(false); } }
  return <><div className={styles.tabs} role="tablist" aria-label="Étape de revue"><button aria-selected={mode === 'submit'} onClick={() => setMode('submit')}>1. Soumettre</button><button aria-selected={mode === 'review'} onClick={() => setMode('review')}>2. Émettre un avis</button><button aria-selected={mode === 'decide'} onClick={() => setMode('decide')}>3. Décider</button></div><div className={styles.grid}><section className={styles.card}><h2>{mode === 'submit' ? 'Nouvelle revue' : mode === 'review' ? 'Avis du réviseur' : 'Décision du Checker'}</h2><form className={styles.form} onSubmit={submit}>{mode === 'submit' ? <><label className={styles.field}>Type de ressource<input value={resourceType} onChange={(e) => setResourceType(e.target.value.toUpperCase())} /></label><label className={styles.field}>Identifiant de ressource<input value={resourceId} onChange={(e) => setResourceId(e.target.value)} /></label></> : <><label className={styles.field}>Identifiant de revue<input value={reviewId} onChange={(e) => setReviewId(e.target.value)} /></label>{mode === 'review' ? <label className={styles.field}>Avis<textarea value={opinion} onChange={(e) => setOpinion(e.target.value)} /></label> : <><label className={styles.field}>Décision<select value={decision} onChange={(e) => setDecision(e.target.value)}><option value="APPROVED">Approuver</option><option value="REJECTED">Rejeter</option></select></label><label className={styles.field}>Justification<textarea value={justification} onChange={(e) => setJustification(e.target.value)} /></label><label className={styles.field}>UUID de la preuve documentaire<input value={evidenceDocumentId} onChange={(e) => setEvidenceDocumentId(e.target.value)} /></label></>}</>}<button className={styles.button} disabled={busy}>{busy ? 'Transmission…' : 'Enregistrer l’étape'}</button></form>{error && <p className={`${styles.notice} ${styles.error}`} role="alert">{error}</p>}</section><section className={styles.card}><h2>État de la revue</h2>{result ? <div className={styles.product}><span className={styles.badge}>{result.state}</span><dl><dt>Revue</dt><dd>{result.reviewId}</dd><dt>Étape</dt><dd>{mode}</dd></dl></div> : <p className={styles.hint}>Chaque rôle ne modifie que son étape ; le backend contrôle les transitions et les autorisations.</p>}</section></div></>;
}
