import { describe, expect, it } from 'vitest';
import { ExclusiveRiskOperation, LatestRiskRead } from './async-operation';
const noop=()=>undefined;
function deferred<T>(){let resolve!:(value:T)=>void;let reject!:(reason?:unknown)=>void;const promise=new Promise<T>((res,rej)=>{resolve=res;reject=rej});return{promise,resolve,reject}}
describe('risk interactions',()=>{
  it('prevents double commands and exposes busy then success',async()=>{const pending=deferred<string>();const events:string[]=[];let calls=0;const manager=new ExclusiveRiskOperation();const callbacks={loading:()=>events.push('busy'),success:(value:string)=>events.push(value),failure:noop,settled:()=>events.push('idle')};const first=manager.run(()=>{calls++;return pending.promise},callbacks,'failure');expect(await manager.run(async()=>{calls++;return'duplicate'},callbacks,'failure')).toBe(false);pending.resolve('success');await first;expect(calls).toBe(1);expect(events).toEqual(['busy','success','idle'])});
  it('exposes a current correlated error then clears busy',async()=>{const events:string[]=[];await new ExclusiveRiskOperation().run(async()=>{throw new Error('DCR refusé (référence : corr-9)')},{loading:()=>events.push('busy'),success:noop,failure:(message)=>events.push(message),settled:()=>events.push('idle')},'fallback');expect(events).toEqual(['busy','DCR refusé (référence : corr-9)','idle'])});
  it('aborts and ignores the old pool dashboard response',async()=>{const old=deferred<string>(),current=deferred<string>();const signals:AbortSignal[]=[];const values:string[]=[];const manager=new LatestRiskRead();const callbacks={loading:noop,success:(value:string)=>values.push(value),failure:noop,settled:noop};const stale=manager.run((signal)=>{signals.push(signal);return old.promise},callbacks,'failure');const latest=manager.run((signal)=>{signals.push(signal);return current.promise},callbacks,'failure');expect(signals[0]?.aborted).toBe(true);current.resolve('POOL-B');await latest;old.resolve('POOL-A');await stale;expect(values).toEqual(['POOL-B'])});
  it('invalidates an in-flight dashboard when the pool input changes',async()=>{const pending=deferred<string>();const values:string[]=[];const signals:AbortSignal[]=[];const manager=new LatestRiskRead();const request=manager.run((signal)=>{signals.push(signal);return pending.promise},{loading:noop,success:(value:string)=>values.push(value),failure:noop,settled:noop},'failure');manager.cancel();expect(signals[0]?.aborted).toBe(true);pending.resolve('OLD-POOL');await request;expect(values).toEqual([])});
});
