'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { calculateDcr, validDcrCommand, type DcrCalculationCommand, type DcrCalculationResult } from './risk-api';
import { ExclusiveRiskOperation } from './async-operation';
import { RiskError, RiskStatus } from './risk-feedback';
import styles from '../products/products.module.css';
const empty: DcrCalculationCommand = { poolId: '', businessDate: new Date().toISOString().slice(0, 10), currency: 'DZD', capitalDurationAmount: '', riskWeightedDurationAmount: '', threshold: '1.00', formulaVersion: 'DCR-1.0', inputChecksumSha256: '' };
export function RiskConsole() {
  const [command, setCommand] = useState(empty), [result, setResult] = useState<DcrCalculationResult>(), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message,setMessage]=useState('');
  const operations=useRef<ExclusiveRiskOperation>(null);
  if(!operations.current)operations.current=new ExclusiveRiskOperation();
  useEffect(()=>()=>operations.current?.cancel(),[]);
  const change = (key: keyof DcrCalculationCommand, value: string) => setCommand({ ...command, [key]: value });
  async function submit(event: FormEvent) { event.preventDefault(); setError('');setMessage(''); if (!validDcrCommand(command)) return setError('Vérifiez le pool, les montants positifs, la devise, la date, la formule et le checksum SHA-256.'); const snapshot={...command}; await operations.current!.run(()=>calculateDcr(snapshot),{loading:()=>{setResult(undefined);setBusy(true)},success:(value)=>{setResult(value);setMessage('Calcul DCR terminé.')},failure:setError,settled:()=>setBusy(false)},'Le calcul DCR a échoué.'); }
  return <div className={styles.grid} aria-busy={busy}><section className={styles.card}><h2>Calcul du DCR</h2><form className={styles.form} onSubmit={submit}><label className={styles.field}>Pool<input disabled={busy} value={command.poolId} onChange={(e) => change('poolId', e.target.value)} required /></label><div className={styles.row}><label className={styles.field}>Date métier<input disabled={busy} required type="date" value={command.businessDate} onChange={(e) => change('businessDate', e.target.value)} /></label><label className={styles.field}>Devise<input disabled={busy} required value={command.currency} maxLength={3} onChange={(e) => change('currency', e.target.value.toUpperCase())} /></label></div><div className={styles.row}><label className={styles.field}>Capital duration<input disabled={busy} required inputMode="decimal" value={command.capitalDurationAmount} onChange={(e) => change('capitalDurationAmount', e.target.value)} /></label><label className={styles.field}>Duration pondérée du risque<input disabled={busy} required inputMode="decimal" value={command.riskWeightedDurationAmount} onChange={(e) => change('riskWeightedDurationAmount', e.target.value)} /></label></div><div className={styles.row}><label className={styles.field}>Seuil<input disabled={busy} required inputMode="decimal" value={command.threshold} onChange={(e) => change('threshold', e.target.value)} /></label><label className={styles.field}>Version de formule<input disabled={busy} required value={command.formulaVersion} onChange={(e) => change('formulaVersion', e.target.value)} /></label></div><label className={styles.field}>Checksum SHA-256 des entrées<input disabled={busy} required spellCheck={false} className={styles.checksum} value={command.inputChecksumSha256} onChange={(e) => change('inputChecksumSha256', e.target.value.toLowerCase())} /></label><button className={styles.button} disabled={busy}>{busy ? 'Calcul…' : 'Calculer le DCR'}</button></form><RiskError message={error}/><RiskStatus message={message}/></section><section className={styles.card}><h2>Résultat traçable</h2>{result ? <div className={styles.product}><span className={styles.badge}>{result.state}</span><dl><dt>DCR</dt><dd>{result.value}</dd><dt>Seuil</dt><dd>{result.threshold}</dd><dt>Calcul</dt><dd>{result.dcrCalculationId}</dd></dl></div> : <p className={styles.hint}>Le résultat et son identifiant de preuve apparaîtront après calcul par le moteur backend.</p>}</section></div>;
}
