'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { runStress, validStressCommand, type StressScenarioCommand, type StressScenarioResult } from './risk-api';
import { ExclusiveRiskOperation } from './async-operation';
import { RiskError, RiskStatus } from './risk-feedback';
import styles from '../products/products.module.css';
export function StressConsole() {
  const [scenarioCode, setScenarioCode] = useState('LIQUIDITY_STRESS'), [businessDate, setBusinessDate] = useState(new Date().toISOString().slice(0, 10)), [currency, setCurrency] = useState('DZD'), [baseAmount, setBaseAmount] = useState(''), [bucket, setBucket] = useState('LIQUIDITY'), [basisPoints, setBasisPoints] = useState('-200'), [engineVersion, setEngineVersion] = useState('STRESS-1.0'), [checksum, setChecksum] = useState(''), [result, setResult] = useState<StressScenarioResult>(), [busy, setBusy] = useState(false), [error, setError] = useState(''),[message,setMessage]=useState('');
  const operations=useRef<ExclusiveRiskOperation>(null);
  if(!operations.current)operations.current=new ExclusiveRiskOperation();
  useEffect(()=>()=>operations.current?.cancel(),[]);
  function command(): StressScenarioCommand { return { scenarioCode, businessDate, currency, baseAmount, shocks: [{ bucket, basisPoints: Number(basisPoints) }], engineVersion, inputChecksumSha256: checksum }; }
  async function submit(event: FormEvent) { event.preventDefault(); const input = command(); setError('');setMessage(''); if (!validStressCommand(input)) return setError('Vérifiez les codes, la date, le montant positif, le choc entre −10 000 et 10 000 pb, la version et le checksum SHA-256.'); await operations.current!.run(()=>runStress(input),{loading:()=>{setResult(undefined);setBusy(true)},success:(value)=>{setResult(value);setMessage('Scénario de stress terminé.')},failure:setError,settled:()=>setBusy(false)},'Le scénario de stress a échoué.'); }
  return <div className={styles.grid} aria-busy={busy}><section className={styles.card}><h2>Scénario de stress</h2><form className={styles.form} onSubmit={submit}><div className={styles.row}><label className={styles.field}>Code scénario<input disabled={busy} required value={scenarioCode} onChange={(e) => setScenarioCode(e.target.value.toUpperCase())} /></label><label className={styles.field}>Date métier<input disabled={busy} required type="date" value={businessDate} onChange={(e) => setBusinessDate(e.target.value)} /></label></div><div className={styles.row}><label className={styles.field}>Montant de base<input disabled={busy} required inputMode="decimal" value={baseAmount} onChange={(e) => setBaseAmount(e.target.value)} /></label><label className={styles.field}>Devise<input disabled={busy} required maxLength={3} value={currency} onChange={(e) => setCurrency(e.target.value.toUpperCase())} /></label></div><div className={styles.row}><label className={styles.field}>Segment de choc<input disabled={busy} required value={bucket} onChange={(e) => setBucket(e.target.value.toUpperCase())} /></label><label className={styles.field}>Points de base<input disabled={busy} required type="number" min={-10000} max={10000} step={1} value={basisPoints} onChange={(e) => setBasisPoints(e.target.value)} /></label></div><label className={styles.field}>Version moteur<input disabled={busy} required value={engineVersion} onChange={(e) => setEngineVersion(e.target.value)} /></label><label className={styles.field}>Checksum SHA-256 des entrées<input disabled={busy} required spellCheck={false} className={styles.checksum} value={checksum} onChange={(e) => setChecksum(e.target.value.toLowerCase())} /></label><button className={styles.button} disabled={busy}>{busy ? 'Simulation…' : 'Exécuter le stress'}</button></form><RiskError message={error}/><RiskStatus message={message}/></section><section className={styles.card}><h2>Impacts calculés</h2>{result ? <div className={styles.product}><span className={styles.badge}>{result.state}</span><dl><dt>Scénario</dt><dd>{result.stressScenarioId}</dd></dl><ul className={styles.referenceList}>{result.results.map((line) => <li key={`${line.bucket}-${line.basisPoints}`}><div><strong>{line.bucket}</strong><small>{line.basisPoints} pb</small></div><span>{line.stressedAmount}</span><span>{line.impactAmount}</span></li>)}</ul></div> : <p className={styles.hint}>Les montants stressés et leurs impacts seront calculés par le moteur backend.</p>}</section></div>;
}
