import type { ComplianceArbitration, ComplianceReference, CreateComplianceReference, RegulatoryRule } from '@bank/pms-api-client';
export type { ComplianceArbitration, ComplianceReference, CreateComplianceReference, RegulatoryRule };
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function exactComplianceDate(value: string): boolean { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value; }
export function referenceFieldErrors(value: CreateComplianceReference): Partial<Record<keyof CreateComplianceReference, string>> { const errors: Partial<Record<keyof CreateComplianceReference, string>> = {}; if (!['BA', 'SHARIA_COMMITTEE', 'AAOIFI', 'IFSB'].includes(value.source)) errors.source = 'Sélectionnez une autorité reconnue.'; if (!/^[A-Za-z0-9._/-]{2,80}$/.test(value.referenceCode)) errors.referenceCode = 'Le code doit contenir 2 à 80 caractères autorisés.'; if (!value.version.trim()) errors.version = 'La version est obligatoire.'; if (value.title.trim().length < 3) errors.title = 'Le titre doit contenir au moins 3 caractères.'; if (!exactComplianceDate(value.effectiveFrom)) errors.effectiveFrom = 'Saisissez une date de début valide.'; if (value.effectiveTo && (!exactComplianceDate(value.effectiveTo) || value.effectiveTo < value.effectiveFrom)) errors.effectiveTo = 'La date de fin doit être valide et postérieure au début.'; return errors; }
export function arbitrationFieldErrors(value: ComplianceArbitration): Partial<Record<keyof ComplianceArbitration, string>> { const errors: Partial<Record<keyof ComplianceArbitration, string>> = {}; if (!uuid.test(value.selectedReferenceId)) errors.selectedReferenceId = 'Saisissez un UUID de référence valide.'; if (!uuid.test(value.rejectedReferenceId)) errors.rejectedReferenceId = 'Saisissez un UUID de référence valide.'; if (!errors.selectedReferenceId && value.selectedReferenceId === value.rejectedReferenceId) { errors.selectedReferenceId = 'Les références doivent être distinctes.'; errors.rejectedReferenceId = 'Les références doivent être distinctes.'; } if (value.rationale.trim().length < 20) errors.rationale = 'La motivation doit contenir au moins 20 caractères.'; return errors; }
export function validReference(value: CreateComplianceReference): boolean { return Object.keys(referenceFieldErrors(value)).length === 0; }
export function validArbitration(value: ComplianceArbitration): boolean { return Object.keys(arbitrationFieldErrors(value)).length === 0; }
async function request<T>(path: string, body?: unknown): Promise<T> { const response = await fetch(`/api/core/${path}`, body === undefined ? undefined : { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify(body) }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) { const problem = (payload ?? {}) as { detail?: string; title?: string; correlationId?: string }; const message = problem.detail ?? problem.title ?? `Erreur HTTP ${response.status}`; const correlationId = problem.correlationId ?? response.headers.get('x-correlation-id'); throw new Error(correlationId ? `${message} (référence : ${correlationId})` : message); } return payload as T; }
export const createReference = (value: CreateComplianceReference) => request<ComplianceReference>('products/compliance-references', value);
export const arbitrate = (productId: string, value: ComplianceArbitration) => request<{ arbitrated: true }>(`products/${encodeURIComponent(productId)}/compliance-arbitrations`, value);
export const getRule = (ruleCode: string, businessDate: string) => request<RegulatoryRule>(`reference-data/regulatory-rules/${encodeURIComponent(ruleCode)}?${new URLSearchParams({ businessDate })}`);
