import type { ComplianceArbitration, ComplianceReference, CreateComplianceReference, RegulatoryRule } from '@bank/pms-api-client';
export type { ComplianceArbitration, ComplianceReference, CreateComplianceReference, RegulatoryRule };
const date = /^\d{4}-\d{2}-\d{2}$/, uuid = /^[0-9a-f-]{36}$/i;
export function validReference(value: CreateComplianceReference): boolean { return ['BA', 'SHARIA_COMMITTEE', 'AAOIFI', 'IFSB'].includes(value.source) && /^[A-Za-z0-9._/-]{2,80}$/.test(value.referenceCode) && value.version.trim().length > 0 && value.title.trim().length >= 3 && date.test(value.effectiveFrom) && (!value.effectiveTo || date.test(value.effectiveTo) && value.effectiveTo >= value.effectiveFrom); }
export function validArbitration(value: ComplianceArbitration): boolean { return uuid.test(value.selectedReferenceId) && uuid.test(value.rejectedReferenceId) && value.selectedReferenceId !== value.rejectedReferenceId && value.rationale.trim().length >= 10; }
async function request<T>(path: string, body?: unknown): Promise<T> { const response = await fetch(`/api/core/${path}`, body === undefined ? undefined : { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify(body) }); const payload: unknown = await response.json().catch(() => undefined); if (!response.ok) { const problem = (payload ?? {}) as { detail?: string; title?: string }; throw new Error(problem.detail ?? problem.title ?? `Erreur HTTP ${response.status}`); } return payload as T; }
export const createReference = (value: CreateComplianceReference) => request<ComplianceReference>('products/compliance-references', value);
export const arbitrate = (productId: string, value: ComplianceArbitration) => request<{ arbitrated: true }>(`products/${encodeURIComponent(productId)}/compliance-arbitrations`, value);
export const getRule = (ruleCode: string, businessDate: string) => request<RegulatoryRule>(`reference-data/regulatory-rules/${encodeURIComponent(ruleCode)}?${new URLSearchParams({ businessDate })}`);
