'use client';
import { type FormEvent, useEffect, useRef, useState } from 'react';
import { solveQuotation, validQuotation, type QuotationCommand, type QuotationResult } from './quotation-api';
import styles from '../products/products.module.css';
type BasisType = QuotationCommand['basis']['type'];
const labels: Record<BasisType, string> = { GLOBAL_POOL: 'Pool global', FINANCING_TYPE: 'Type de financement', DESIGNATED_FINANCING: 'Financement désigné', CUSTOMER: 'Client', SECTOR: 'Secteur' };
export function QuotationConsole() {
  const [placementAmount, setPlacementAmount] = useState(''), [targetRate, setTargetRate] = useState(''), [basisType, setBasisType] = useState<BasisType>('GLOBAL_POOL'), [reference, setReference] = useState(''), [result, setResult] = useState<QuotationResult>(), [busy, setBusy] = useState(false), [attempted, setAttempted] = useState(false), [error, setError] = useState('');
  const inFlight = useRef<AbortController | undefined>(undefined); const sequence = useRef(0);
  useEffect(() => () => { sequence.current += 1; inFlight.current?.abort(); inFlight.current = undefined; }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setAttempted(true); if (inFlight.current) return; const command: QuotationCommand = { placementAmount: placementAmount.trim(), targetNetRatePercent: targetRate.trim(), basis: { type: basisType, ...(basisType === 'GLOBAL_POOL' ? {} : { reference: reference.trim() }) } }; if (!validQuotation(command)) { setError('Montant, taux positif et référence du périmètre sont requis.'); return; } const controller = new AbortController(); const current = ++sequence.current; inFlight.current = controller; setBusy(true); setError(''); setResult(undefined); try { const value = await solveQuotation(command, controller.signal); if (current !== sequence.current || controller.signal.aborted) return; setResult(value); } catch (cause) { if (current !== sequence.current || controller.signal.aborted) return; setError(cause instanceof Error ? cause.message : 'Erreur inattendue.'); } finally { if (current === sequence.current) { inFlight.current = undefined; setBusy(false); } } }
  const amountInvalid = attempted && !/^(?:0|[1-9]\d*)(?:\.\d+)?$/.test(placementAmount.trim()); const rateInvalid = attempted && !/^(?:0|[1-9]\d*)(?:\.\d+)?$/.test(targetRate.trim()); const referenceInvalid = attempted && basisType !== 'GLOBAL_POOL' && !reference.trim();
  return <div className={styles.grid} aria-busy={busy}><section className={styles.card} aria-labelledby="quotation-form-title" aria-busy={busy}><h2 id="quotation-form-title">Objectif commercial</h2><form className={styles.form} onSubmit={(event) => void submit(event)} noValidate><label className={styles.field} htmlFor="quotation-placement-amount">Montant du placement (DZD)<input id="quotation-placement-amount" inputMode="decimal" required aria-invalid={amountInvalid} aria-describedby={error ? 'quotation-error' : undefined} value={placementAmount} onChange={(event) => { setPlacementAmount(event.target.value); setError(''); }} /></label><label className={styles.field} htmlFor="quotation-target-rate">Taux net cible (%)<input id="quotation-target-rate" inputMode="decimal" required aria-invalid={rateInvalid} aria-describedby={error ? 'quotation-error' : undefined} value={targetRate} onChange={(event) => { setTargetRate(event.target.value); setError(''); }} /></label><label className={styles.field} htmlFor="quotation-basis">Base de calcul<select id="quotation-basis" value={basisType} onChange={(event) => { setBasisType(event.target.value as BasisType); setError(''); }}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{basisType !== 'GLOBAL_POOL' && <label className={styles.field} htmlFor="quotation-reference">Référence de la base<input id="quotation-reference" required aria-invalid={referenceInvalid} aria-describedby={error ? 'quotation-error' : undefined} value={reference} onChange={(event) => { setReference(event.target.value); setError(''); }} /></label>}<button className={styles.button} type="submit" disabled={busy} aria-disabled={busy}>{busy ? 'Calcul en cours…' : 'Résoudre le taux cible'}</button></form>{error && <p id="quotation-error" className={`${styles.notice} ${styles.error}`} role="alert" aria-live="assertive">{error}</p>}</section><section className={styles.card} aria-labelledby="quotation-result-title" aria-live="polite"><h2 id="quotation-result-title">Verdict réconcilié</h2>{!result ? <p className={styles.hint}>Le moteur utilise exclusivement les capacités et résultats certifiés côté serveur.</p> : <div className={styles.product}><span className={styles.badge}>{result.verdict}</span><dl><dt>Nisba investisseur</dt><dd>{result.recommendedInvestorNisbaPercent}%</dd><dt>Soutien requis</dt><dd>{result.requiredSupportAmount} DZD</dd><dt>Capacité maximale</dt><dd>{result.maximumBasisCapacity} DZD</dd><dt>Gouvernance</dt><dd>{result.governance}</dd><dt>Comptabilité séparée</dt><dd>{result.segregatedAccountingRequired ? 'Requise' : 'Non requise'}</dd></dl><p className={styles.notice}>{result.notice}</p></div>}</section></div>;
}
