'use client';
import { type FormEvent, useState } from 'react';
import { solveQuotation, validQuotation, type QuotationCommand, type QuotationResult } from './quotation-api';
import styles from '../products/products.module.css';
type BasisType = QuotationCommand['basis']['type'];
const labels: Record<BasisType, string> = { GLOBAL_POOL: 'Pool global', FINANCING_TYPE: 'Type de financement', DESIGNATED_FINANCING: 'Financement désigné', CUSTOMER: 'Client', SECTOR: 'Secteur' };
export function QuotationConsole() {
  const [placementAmount, setPlacementAmount] = useState(''), [targetRate, setTargetRate] = useState(''), [basisType, setBasisType] = useState<BasisType>('GLOBAL_POOL'), [reference, setReference] = useState(''), [result, setResult] = useState<QuotationResult>(), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); const command: QuotationCommand = { placementAmount, targetNetRatePercent: targetRate, basis: { type: basisType, ...(basisType === 'GLOBAL_POOL' ? {} : { reference }) } }; if (!validQuotation(command)) return setError('Montant, taux positif et référence du périmètre sont requis.'); setBusy(true); setError(''); setResult(undefined); try { setResult(await solveQuotation(command)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erreur inattendue.'); } finally { setBusy(false); } }
  return <div className={styles.grid}><section className={styles.card}><h2>Objectif commercial</h2><form className={styles.form} onSubmit={(event) => void submit(event)}><label className={styles.field}>Montant du placement (DZD)<input inputMode="decimal" value={placementAmount} onChange={(event) => setPlacementAmount(event.target.value)} /></label><label className={styles.field}>Taux net cible (%)<input inputMode="decimal" value={targetRate} onChange={(event) => setTargetRate(event.target.value)} /></label><label className={styles.field}>Base de calcul<select value={basisType} onChange={(event) => setBasisType(event.target.value as BasisType)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{basisType !== 'GLOBAL_POOL' && <label className={styles.field}>Référence de la base<input value={reference} onChange={(event) => setReference(event.target.value)} /></label>}<button className={styles.button} disabled={busy}>{busy ? 'Calcul en cours…' : 'Résoudre le taux cible'}</button></form>{error && <p className={`${styles.notice} ${styles.error}`}>{error}</p>}</section><section className={styles.card}><h2>Verdict réconcilié</h2>{!result ? <p className={styles.hint}>Le moteur utilise exclusivement les capacités et résultats certifiés côté serveur.</p> : <div className={styles.product}><span className={styles.badge}>{result.verdict}</span><dl><dt>Nisba investisseur</dt><dd>{result.recommendedInvestorNisbaPercent}%</dd><dt>Soutien requis</dt><dd>{result.requiredSupportAmount} DZD</dd><dt>Capacité maximale</dt><dd>{result.maximumBasisCapacity} DZD</dd><dt>Gouvernance</dt><dd>{result.governance}</dd><dt>Comptabilité séparée</dt><dd>{result.segregatedAccountingRequired ? 'Requise' : 'Non requise'}</dd></dl><p className={styles.notice}>{result.notice}</p></div>}</section></div>;
}
