'use client';
import { FormEvent, useEffect, useState } from 'react';
import { loadCbsQuality, qualitySummary, type CbsDataQualityBatch } from './cbs-quality-api';
import styles from './cbs-quality.module.css';
export function CbsQualityConsole(){const[rows,setRows]=useState<readonly CbsDataQualityBatch[]>([]),[filters,setFilters]=useState<{businessDate?:string;state?:string}>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');loadCbsQuality(filters,controller.signal).then(setRows).catch((cause:unknown)=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'Chargement impossible.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[filters]);const summary=qualitySummary(rows);
function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setFilters({businessDate:String(data.get('businessDate')||'')||undefined,state:String(data.get('state')||'')||undefined})}
return <><form className={styles.filters} onSubmit={submit} aria-label="Filtres de qualité CBS"><label>Date métier<input name="businessDate" type="date"/></label><label>État<select name="state"><option value="">Tous les états</option><option>VALIDATED</option><option>REJECTED</option><option>QUARANTINED</option><option>STAGED</option></select></label><button>Appliquer</button></form><section className={styles.summary} aria-label="Synthèse qualité"><Metric label="Lots contrôlés" value={summary.batches}/><Metric label="Lots en anomalie" value={summary.rejected} alert={summary.rejected>0}/><Metric label="Erreurs" value={summary.errors} alert={summary.errors>0}/><Metric label="Avertissements" value={summary.warnings}/></section>
{loading?<div className={styles.skeleton} aria-label="Chargement des lots" aria-busy="true">{[1,2,3].map(v=><i key={v}/>)}</div>:error?<div className={styles.feedback} role="alert"><strong>Données indisponibles</strong><p>{error}</p><button onClick={()=>setFilters(current=>({...current}))}>Réessayer</button></div>:rows.length===0?<div className={styles.feedback}><strong>Aucun lot trouvé</strong><p>Modifiez les filtres ou attendez la prochaine ingestion CBS.</p></div>:<div className={styles.tableWrap}><table><caption>Résultats des contrôles CBS</caption><thead><tr><th>Date</th><th>Flux</th><th>Séquence</th><th>État</th><th>Lignes attendues</th><th>Solde manifeste</th><th>Erreurs</th><th>Dernier contrôle</th></tr></thead><tbody>{rows.map(row=><tr key={row.batchId}><td>{row.businessDate}</td><td><strong>{row.flowType}</strong><small>{row.sourceCode}</small></td><td>{row.sequenceNumber}</td><td><span className={`${styles.state} ${stateClass(row.state)}`}>{row.state}</span></td><td>{row.manifestRowCount??'Non renseigné'}</td><td className={styles.number}>{row.manifestBalanceTotal??'Non renseigné'}</td><td><b className={row.errorCount?styles.errorCount:undefined}>{row.errorCount}</b>{row.warningCount>0&&<small>{row.warningCount} avert.</small>}</td><td>{row.lastControlAt?new Intl.DateTimeFormat('fr-DZ',{dateStyle:'short',timeStyle:'short'}).format(new Date(row.lastControlAt)):'En attente'}</td></tr>)}</tbody></table></div>}</>}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <article><span>{label}</span><strong className={alert?styles.alert:undefined}>{value}</strong></article>}function stateClass(state:string){return state==='VALIDATED'?styles.valid:['REJECTED','QUARANTINED'].includes(state)?styles.invalid:styles.pending}
