'use client';
import { useEffect, useState } from 'react';
import { detokenize, rotateToken, searchToken, tokenize, validDigest, validPurpose, validToken, type TokenizedValue } from './token-api';
import styles from '../products/products.module.css';
type Mode = 'tokenize' | 'search' | 'detokenize' | 'rotate';
export function TokenConsole() {
  const [mode, setMode] = useState<Mode>('tokenize'), [value, setValue] = useState(''), [dataClass, setDataClass] = useState('CUSTOMER_ID'), [purpose, setPurpose] = useState(''), [result, setResult] = useState<TokenizedValue>(), [clearValue, setClearValue] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { if (!clearValue) return; const timer = window.setTimeout(() => setClearValue(''), 30_000); return () => window.clearTimeout(timer); }, [clearValue]);
  async function submit() { if (!validPurpose(purpose)) return setError('Une finalité opérationnelle explicite est obligatoire.'); if ((mode === 'detokenize' || mode === 'rotate') && !validToken(value)) return setError('Jeton invalide.'); if (mode === 'search' && !validDigest(value)) return setError('Empreinte SHA-256 invalide.'); if (mode === 'tokenize' && !value) return setError('Valeur à protéger obligatoire.'); setBusy(true); setError(''); setResult(undefined); setClearValue(''); try { if (mode === 'tokenize') setResult(await tokenize({ value, dataClass, purpose })); else if (mode === 'search') setResult(await searchToken({ searchDigestSha256: value, dataClass, purpose })); else if (mode === 'rotate') setResult(await rotateToken({ token: value, purpose })); else setClearValue((await detokenize({ token: value, purpose })).value); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erreur inattendue.'); } finally { setBusy(false); } }
  return <div className={styles.grid}><section className={styles.card}><h2>Opération sécurisée</h2><div className={styles.tabs} role="tablist">{(['tokenize', 'search', 'detokenize', 'rotate'] as const).map((item) => <button key={item} role="tab" aria-selected={mode === item} onClick={() => { setMode(item); setValue(''); }}>{item === 'tokenize' ? 'Tokeniser' : item === 'search' ? 'Rechercher' : item === 'detokenize' ? 'Déchiffrer' : 'Rotation'}</button>)}</div><div className={styles.form}>{(mode === 'tokenize' || mode === 'search') && <label className={styles.field}>Classe de données<select value={dataClass} onChange={(event) => setDataClass(event.target.value)}><option>CUSTOMER_ID</option><option>NATIONAL_ID</option><option>BENEFICIAL_OWNER</option><option>REPRESENTATIVE_ID</option></select></label>}<label className={styles.field}>{mode === 'tokenize' ? 'Valeur personnelle' : mode === 'search' ? 'Empreinte SHA-256' : 'Jeton'}<input type={mode === 'tokenize' ? 'password' : 'text'} autoComplete="off" value={value} onChange={(event) => setValue(event.target.value)} /></label><label className={styles.field}>Finalité auditée<textarea value={purpose} onChange={(event) => setPurpose(event.target.value)} /></label><button className={styles.button} disabled={busy} onClick={() => void submit()}>{busy ? 'Traitement…' : 'Exécuter'}</button></div>{error && <p className={`${styles.notice} ${styles.error}`}>{error}</p>}</section><section className={styles.card}><h2>Résultat protégé</h2>{result ? <div className={styles.product}><span className={styles.badge}>{result.dataClass}</span><dl><dt>Jeton</dt><dd className={styles.checksum}>{result.token}</dd><dt>Version de clé</dt><dd>{result.vaultKeyVersion}</dd></dl></div> : clearValue ? <div className={styles.notice}><strong>Valeur claire temporaire</strong><p>{clearValue}</p><small>Effacement automatique de l’affichage dans 30 secondes.</small></div> : <p className={styles.hint}>Aucune donnée claire n’est conservée par cette interface. Chaque opération est autorisée et auditée côté serveur.</p>}</section></div>;
}
