'use client';
import { type FormEvent, useEffect, useRef, useState } from 'react';
import { adjustIncome, evaluateCharges, importIncome, listIncome, validAdjustment, validIncome, type ChargeEvaluation, type IncomeAdjustment, type RecognizedIncome } from './revenue-api';
import styles from '../products/products.module.css';
const today = new Date().toISOString().slice(0, 10);
export function RevenuesConsole() {
  const [poolId, setPoolId] = useState(''), [businessDate, setBusinessDate] = useState(today), [assetId, setAssetId] = useState(''), [sourceReference, setSourceReference] = useState(''), [amount, setAmount] = useState(''), [incomeType, setIncomeType] = useState('MURABAHA'), [incomes, setIncomes] = useState<readonly RecognizedIncome[]>([]), [evaluation, setEvaluation] = useState<ChargeEvaluation>(), [selected, setSelected] = useState(''), [adjustmentAmount, setAdjustmentAmount] = useState(''), [reason, setReason] = useState(''), [approvalId, setApprovalId] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const inFlight = useRef<AbortController | undefined>(undefined);
  const sequence = useRef(0);
  useEffect(() => () => { sequence.current += 1; inFlight.current?.abort(); inFlight.current = undefined; }, []);
  async function run<T>(work: (signal: AbortSignal) => Promise<T>, done: (value: T) => void, message: string) {
    if (inFlight.current) return;
    const controller = new AbortController();
    const current = ++sequence.current;
    inFlight.current = controller;
    setBusy(true); setError(''); setNotice('');
    try { const value = await work(controller.signal); if (current !== sequence.current || controller.signal.aborted) return; done(value); setNotice(message); }
    catch (cause) { if (current !== sequence.current || controller.signal.aborted) return; setError(cause instanceof Error ? cause.message : 'Erreur inattendue.'); }
    finally { if (current === sequence.current) { inFlight.current = undefined; setBusy(false); } }
  }
  async function load(event: FormEvent) { event.preventDefault(); if (!poolId.trim()) return setError('Le pool est obligatoire.'); await run((signal) => listIncome(poolId.trim(), businessDate, signal), setIncomes, 'Revenus actualisés.'); }
  async function create() { const income: RecognizedIncome = { incomeId: crypto.randomUUID(), sourceSystem: 'CBS', sourceReference: sourceReference.trim(), assetId: assetId.trim(), poolId: poolId.trim(), businessDate, currency: 'DZD', amount: amount.trim(), cashStatus: 'RECEIVED', realizationStatus: 'REALIZED', incomeType: incomeType.trim() }; if (!validIncome(income)) return setError('Revenu invalide : contrôlez les identifiants, la référence et le montant.'); await run((signal) => importIncome(income, signal), (value) => setIncomes((current) => [value, ...current]), 'Revenu importé avec traçabilité.'); }
  async function adjust() { const command: IncomeAdjustment = { adjustmentId: crypto.randomUUID(), incomeId: selected, amount: adjustmentAmount.trim(), reason: reason.trim(), approvalId: approvalId.trim(), businessDate, actorId: 'current-user' }; if (!validAdjustment(command)) return setError('Ajustement invalide : justification (10 caractères) et approbation (16 caractères) requises.'); await run((signal) => adjustIncome(command, signal), () => undefined, 'Ajustement contrôlé enregistré.'); }
  return <div className={styles.grid}>
    <section className={styles.card} aria-busy={busy}><h2>Périmètre de reconnaissance</h2><form className={styles.form} onSubmit={(event) => void load(event)}><label className={styles.field}>Pool<input value={poolId} onChange={(event) => setPoolId(event.target.value)} required aria-describedby="revenue-error" /></label><label className={styles.field}>Date métier<input type="date" value={businessDate} onChange={(event) => setBusinessDate(event.target.value)} required /></label><div className={styles.actions}><button className={styles.button} disabled={busy}>Charger les revenus</button><button type="button" className={`${styles.button} ${styles.secondary}`} disabled={busy || !poolId.trim()} onClick={() => void run((signal) => evaluateCharges(poolId.trim(), businessDate, signal), setEvaluation, 'Charges évaluées.')}>Évaluer les charges</button></div></form>{error && <p id="revenue-error" className={`${styles.notice} ${styles.error}`} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status" aria-live="polite">{notice}</p>}{evaluation && <div className={styles.product}><h2>Charges déductibles</h2><dl><dt>Total pool</dt><dd>{evaluation.poolDeductibleTotal} DZD</dd><dt>Acceptées</dt><dd>{evaluation.accepted.length}</dd><dt>Rejetées</dt><dd>{evaluation.rejected.length}</dd></dl></div>}</section>
    <section className={styles.card}><h2>Importer un revenu reconnu</h2><div className={styles.form}><label className={styles.field}>Actif (UUID)<input value={assetId} onChange={(event) => setAssetId(event.target.value)} /></label><label className={styles.field}>Référence source<input value={sourceReference} onChange={(event) => setSourceReference(event.target.value)} /></label><div className={styles.row}><label className={styles.field}>Montant DZD<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className={styles.field}>Type<input value={incomeType} onChange={(event) => setIncomeType(event.target.value.toUpperCase())} /></label></div><button className={styles.button} disabled={busy || !poolId} onClick={() => void create()}>Importer</button></div><hr className={styles.separator}/><h2>Ajuster avec approbation</h2><div className={styles.form}><label className={styles.field}>Revenu<select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Sélectionner</option>{incomes.map((income) => <option key={income.incomeId} value={income.incomeId}>{income.sourceReference} · {income.amount} {income.currency}</option>)}</select></label><label className={styles.field}>Montant de correction<input value={adjustmentAmount} onChange={(event) => setAdjustmentAmount(event.target.value)} /></label><label className={styles.field}>Justification<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label><label className={styles.field}>Référence d’approbation<input value={approvalId} onChange={(event) => setApprovalId(event.target.value)} /></label><button className={styles.button} disabled={busy || !selected} onClick={() => void adjust()}>Enregistrer l’ajustement</button></div></section>
    <section className={styles.card} style={{ gridColumn: '1 / -1' }} aria-live="polite"><h2>Revenus reconnus ({incomes.length})</h2>{incomes.length === 0 ? <p className={styles.hint}>Aucun revenu chargé pour ce périmètre.</p> : <ul className={styles.referenceList}>{incomes.map((income) => <li key={income.incomeId}><div><strong>{income.sourceReference}</strong><small>{income.incomeType} · actif {income.assetId}</small></div><span className={styles.badge}>{income.cashStatus}</span><strong>{income.amount} {income.currency}</strong></li>)}</ul>}</section>
  </div>;
}
